name: Continuous Integration

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18, 20]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run type check
      run: npx tsc --noEmit
      
    - name: Run linting
      run: npm run lint || echo "Linting not configured"
      
    - name: Build application
      run: npm run build
      env:
        DATABASE_URL: "file:./test.db"
        NEXTAUTH_URL: "http://localhost:3000"
        NEXTAUTH_SECRET: "test-secret"
        
    - name: Test database connection
      run: npx prisma db push --accept-data-loss
      env:
        DATABASE_URL: "file:./test.db"
        
    - name: Generate Prisma Client
      run: npx prisma generate
      env:
        DATABASE_URL: "file:./test.db"

  security-scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run security audit
      run: npm audit --audit-level moderate
      
    - name: Run dependency check
      run: npx audit-ci --config audit-ci.json || echo "audit-ci not configured"
